### ISSUE TITLE
No matching distribution found for hiveplote

### ISSUE THREAD

**Issue by baditaflorin** [ericmjl/hiveplot#14]
sudo -H pip3 install hiveplote
Collecting hiveplote
  Could not find a version that satisfies the requirement hiveplote (from versions: )
No matching distribution found for hiveplote

Ubuntu 16.04

**Comment by ericmjl** [comment]
Should be `hiveplot`, not `hiveplote`. URL for PyPI package is here: https://pypi.python.org/pypi/hiveplot

Alternatively, install directly from repo: `pip install git+https://github.com/ericmjl/hiveplot.git`
