### ISSUE TITLE
hiveplot requires matplotlib 1.5 matplotlib 2.0 is present

### ISSUE THREAD

**Issue by uli22** [ericmjl/hiveplot#19]
Hi,
I wanted to pip install hiveplot and did not succeed as matplotlib is not right version. Is it possible to install using matplotlib 2.0 ?
Thank you

**Comment by ericmjl** [comment]
@uli22 thanks for the ping. I'll update the requirements file, but do note that I'm planning on moving hiveplot to [nxviz](https://github.com/ericmjl/nxviz) in the future. Give me a few minutes to get things going.

**Comment by uli22** [comment]
Thanks for quick answer. As a workaround I unpacked files fr whl and copied
in Python/Lib/hiveplot which succeeded in drawing a hiveplot.
Cheers
Uli

Am 18.10.2017 2:14 vorm. schrieb "Eric Ma" <notifications@github.com>:

**Comment by ericmjl** [comment]
@uli22 I just uploaded a new version to PyPI, please let me know if that works!

**Comment by uli22** [comment]
Hi Eric,
I just tested.
pip install hiveplot did not work on win 10
so I downloaded hiveplot-2017.10.17-py2.py3-none-any.whl and pip install
c:\hiveplot-2017.10.17-py2.py3-none-any.whl worked.
But in between I had uodated matplotlib to 2.1.0. pip install hiveplot
removed that higher version and replaced again by matplotlib 2.0.0
So hiveplot works now but other users may wish to keep any higher version
of matplotlib.
Thanks for help
Uli

2017-10-18 2:32 GMT+02:00 Eric Ma <notifications@github.com>:

**Comment by ericmjl** [comment]
Oh, I think I know what happened - I pinned matplotlib to 2.0.0 rather than >=2.0.0. Let me update that and see if this works.

**Comment by ericmjl** [comment]
Okay, just uploaded a new version. Tested locally and it works out fine. Please let me know if it works for you!

**Comment by uli22** [comment]
Hi Eric
I testet download whl  file from pypi [hiveplot 2017.10.17.21.7]
and again it uninstalled my matplotlib 2.1.0 and installed 2.0.0

Also I tried to install nxviz and nxviz uninstalled networkx 2.0 and
matplotlib and also downgraded.
I would prefer to only install nxviz and not e.g. pandas and so on.

cheers
Uli

2017-10-18 3:15 GMT+02:00 Eric Ma <notifications@github.com>:

**Comment by ericmjl** [comment]
Those other packages are dependencies for the project, particularly for the examples, which are intentionally packaged together. That said, keep in mind, I’m just releasing this as a favor, while hiveplot is being migrated into nxviz.
