### ISSUE TITLE
Broken Test.ipynb in README.md example

### ISSUE THREAD

**Issue by brainstorm** [ericmjl/hiveplot#20]
http://nbviewer.ipython.org/github/ericmjl/hiveplot/blob/master/test/Tests.ipynb

**Comment by snympi** [comment]
I also get the error that the notebook does not exist any more.

**Comment by ericmjl** [comment]
My apologies! It is located in the `tests/` folder, under `tests/test_data/Tests.ipynb`: https://github.com/ericmjl/hiveplot/blob/master/tests/test_data/Tests.ipynb

I'm in a long-overdue process of migrating this to [`nxviz`](https://github.com/ericmjl/nxviz), so keep your eyes peeled! In the meantime, feel free to hack on `hiveplot` :smile:.

**Comment by snympi** [comment]
Thanks Eric!
