### ISSUE TITLE
multi-layer layout 

### ISSUE THREAD

**Issue by zhaotao1987** [ericmjl/hiveplot#24]
Hi Eric,

Thank you very much for implementing hive plots in python and the tutorial notebooks! 
https://ericmjl.github.io/Network-Analysis-Made-Simple/

I am really curious to find an example for making a multi-layer layout for networks. Something looks like this: 
![image](https://user-images.githubusercontent.com/16197676/63429316-00048200-c41a-11e9-9850-03b6396045db.png)
Is it possible to do so using your python package? Thank you very much!

Best, Tao

**Comment by ericmjl** [comment]
Hi @zhaotao1987,

Thanks for pinging in and for the kind words!

Unfortunately, multi-layer network diagrams are not possible at the moment. The principled thing to do would be to lay out each node in a graph graph on a 2D plane of a matplotlib 3D axes object, and then plot them that way.

I’m unfortunately quite busy at work, so I haven’t had the time to keep hiveplot updated. I am open to pull requests if this is something you’d like to contribute back to the community!

Cheers,
Eric

**Comment by zhaotao1987** [comment]
Hi Eric,

Thank you very much for your reply. 
I understand, I think right now it's already awesome enough. 
I would indeed love to contribute for the multi-layer part if my skills allows me ;-). 
Maybe later..

Best, Tao

**Comment by ericmjl** [comment]
Thanks Tao! I am going to close this issue for now, feel free to reopen if you would like to continue the conversation.
