### ISSUE TITLE
Code in `adjust_angles method`

### ISSUE THREAD

**Issue by empet** [ericmjl/hiveplot#6]
In the `adjust_angles` method (`hiveplot.py`), lines 288, 289, 
it isn't computed the index of a group in the list of node groups, but the angle theta corresponding to that group. Is it OK to compare  `theta` to `len(self.nodes.keys())-1` (line 291 and other lines following below) ?

**Comment by ericmjl** [comment]
@empet: great catch! I think I was accumulating technical debt at that point. I have made fixes to the code. Out of curiosity, which group are you with?
